[tool.poetry]
name = "api-gateway"
version = "1.0.0"
description = "Orchestrateur central du système Helpline (Passerelle API)"
authors = ["Franck <franck@helpline.fr>"]

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.0"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"